package com.bjpowernode.crm.workbench.mapper;

import com.bjpowernode.crm.workbench.domain.FunnelVO;
import com.bjpowernode.crm.workbench.domain.Tran;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TranMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Apr 20 16:45:01 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Apr 20 16:45:01 CST 2023
     */
    int insert(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Apr 20 16:45:01 CST 2023
     */
    int insertSelective(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Apr 20 16:45:01 CST 2023
     */
    Tran selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Apr 20 16:45:01 CST 2023
     */
    int updateByPrimaryKeySelective(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Apr 20 16:45:01 CST 2023
     */
    int updateByPrimaryKey(Tran record);

    int insertTran(Tran tran);

    List<Tran> selectTranByConditionForPage(Map<String,Object> map);

    int selectCountOfTranByCondition(Map<String,Object> map);

    Tran selectTranByTranId(String id);

    int updateTran(Tran tran);

    int deleteTran(@Param("ids") String[] ids);

    List<FunnelVO> selectCountOfTranGroupByStage();

    List<Tran> selectTranByContactsId(String ContactsId);

    int deleteTranById(String id);

    List<Tran> selectTranByCustomerId(String CustomerId);
}